const express  = require('express');
const bcrypt   = require('bcryptjs');
const jwt      = require('jsonwebtoken');
const db       = require('../database/db');
const { verifyToken } = require('../middleware/auth');

const router = express.Router();

const signToken = (user) =>
  jwt.sign(
    {
      id: user.id, name: user.name, email: user.email,
      role: user.role, avatar: user.avatar,
      classId:   user.class_id,
      teacherId: user.teacher_id,
      childId:   user.child_id,
    },
    process.env.JWT_SECRET,
    { expiresIn: '7d' }
  );

// ── POST /api/auth/login ──────────────────────────────────────
router.post('/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password)
      return res.status(400).json({ error: 'البريد الإلكتروني وكلمة المرور مطلوبان' });

    const { rows } = await db.query(
      'SELECT * FROM users WHERE LOWER(email) = LOWER($1)', [email]
    );
    const user = rows[0];
    if (!user) return res.status(401).json({ error: 'البريد الإلكتروني أو كلمة المرور غير صحيحة' });

    const valid = bcrypt.compareSync(password, user.password);
    if (!valid) return res.status(401).json({ error: 'البريد الإلكتروني أو كلمة المرور غير صحيحة' });

    const token = signToken(user);
    const { password: _, ...safeUser } = user;
    res.json({ token, user: safeUser });
  } catch (err) {
    console.error('Login error:', err);
    res.status(500).json({ error: 'خطأ في تسجيل الدخول' });
  }
});

// ── GET /api/auth/verify-code ─────────────────────────────────
// Validates an invite code and returns the linked name for UI preview
// Query: ?code=XXXX-XXXX-XXXX&role=parent|teacher
router.get('/verify-code', async (req, res) => {
  const { code, role } = req.query;
  if (!code || !role) return res.status(400).json({ error: 'الرمز والدور مطلوبان' });

  try {
    if (role === 'parent') {
      const { rows } = await db.query(
        'SELECT id, name, invite_code_hash FROM students WHERE invite_code_hash IS NOT NULL'
      );
      const matched = rows.find((r) => bcrypt.compareSync(code.trim().toUpperCase(), r.invite_code_hash));
      if (!matched) return res.status(404).json({ error: 'رمز الدعوة غير صحيح أو منتهي الصلاحية' });

      const used = await db.query('SELECT id FROM users WHERE child_id = $1', [matched.id]);
      if (used.rows.length > 0) return res.status(409).json({ error: 'تم استخدام هذا الرمز بالفعل' });

      return res.json({ valid: true, studentName: matched.name, studentId: matched.id });
    }

    if (role === 'teacher') {
      const { rows } = await db.query(
        'SELECT id, name, invite_code_hash FROM teachers WHERE invite_code_hash IS NOT NULL'
      );
      const matched = rows.find((r) => bcrypt.compareSync(code.trim().toUpperCase(), r.invite_code_hash));
      if (!matched) return res.status(404).json({ error: 'رمز الدعوة غير صحيح أو منتهي الصلاحية' });

      const used = await db.query('SELECT id FROM users WHERE teacher_id = $1', [matched.id]);
      if (used.rows.length > 0) return res.status(409).json({ error: 'تم استخدام هذا الرمز بالفعل' });

      return res.json({ valid: true, teacherName: matched.name, teacherId: matched.id });
    }

    return res.status(400).json({ error: 'دور غير صالح' });
  } catch (err) {
    console.error('verify-code error:', err);
    res.status(500).json({ error: 'خطأ في التحقق من الرمز' });
  }
});

// ── POST /api/auth/register ───────────────────────────────────
// Manager: uses secret hardcoded code + name
// Parent / Teacher: uses invite code generated by manager
// Helper: validate Saudi-style phone (10 digits, starts with 0)
const isValidPhone = (p) => /^0\d{9}$/.test((p || '').trim());

router.post('/register', async (req, res) => {
  const client = await db.connect();
  try {
    const { email, password, phone, inviteCode, role, name } = req.body;

    if (!role || !['manager', 'parent', 'teacher'].includes(role))
      return res.status(400).json({ error: 'دور غير صالح' });
    if (!email || !password)
      return res.status(400).json({ error: 'البريد الإلكتروني وكلمة المرور مطلوبان' });
    if (password.length < 6)
      return res.status(400).json({ error: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل' });

    const existing = await client.query('SELECT id FROM users WHERE LOWER(email) = LOWER($1)', [email]);
    if (existing.rows.length > 0)
      return res.status(409).json({ error: 'البريد الإلكتروني مستخدم بالفعل' });

    // ── MANAGER ──────────────────────────────────────────────
    if (role === 'manager') {
      const MANAGER_SECRET = 'RAWDAH-ADMIN-2026';
      if ((inviteCode || '').trim().toUpperCase() !== MANAGER_SECRET)
        return res.status(403).json({ error: 'رمز المدير غير صحيح — تواصل مع إدارة الحضانة' });
      if (!name)
        return res.status(400).json({ error: 'اسم المدير مطلوب' });
      await client.query('BEGIN');
      const hashed = bcrypt.hashSync(password, 10);
      const { rows } = await client.query(
        `INSERT INTO users (name, email, password, role, avatar) VALUES ($1, $2, $3, 'manager', '👨‍💼') RETURNING *`,
        [name, email, hashed]
      );
      await client.query(`INSERT INTO activity_log (icon, text, type) VALUES ('👨‍💼', $1, 'user')`, [`مدير جديد: ${name}`]);
      await client.query('COMMIT');
      const token = signToken(rows[0]);
      const { password: _, ...safeUser } = rows[0];
      return res.status(201).json({ token, user: safeUser });
    }

    // ── PARENT / TEACHER — require invite code ────────────────
    if (!inviteCode)
      return res.status(400).json({ error: 'رمز الدعوة مطلوب' });

    const normalizedCode = inviteCode.trim().toUpperCase();

    // ── PARENT ────────────────────────────────────────────────
    if (role === 'parent') {
      if (!phone) return res.status(400).json({ error: 'رقم الجوال مطلوب لتسجيل ولي الأمر' });
      if (!isValidPhone(phone)) return res.status(400).json({ error: 'رقم الجوال يجب أن يكون 10 أرقام ويبدأ بـ 0' });
      if (!name) return res.status(400).json({ error: 'اسم ولي الأمر مطلوب' });

      const { rows: students } = await client.query(
        'SELECT id, name, invite_code_hash FROM students WHERE invite_code_hash IS NOT NULL'
      );
      const student = students.find((s) => bcrypt.compareSync(normalizedCode, s.invite_code_hash));
      if (!student) return res.status(400).json({ error: 'رمز الدعوة غير صحيح' });

      const alreadyUsed = await client.query('SELECT id FROM users WHERE child_id = $1', [student.id]);
      if (alreadyUsed.rows.length > 0)
        return res.status(409).json({ error: 'تم استخدام هذا الرمز بالفعل' });

      await client.query('BEGIN');
      await client.query('UPDATE students SET phone = $1 WHERE id = $2', [phone, student.id]);

      const hashed = bcrypt.hashSync(password, 10);
      const { rows: userRows } = await client.query(
        `INSERT INTO users (name, email, password, role, avatar, child_id, invite_code)
         VALUES ($1, $2, $3, 'parent', '👨', $4, $5) RETURNING *`,
        [name.trim(), email, hashed, student.id, normalizedCode]
      );
      await client.query(
        `INSERT INTO activity_log (icon, text, type) VALUES ('👨', $1, 'user')`,
        [`ولي أمر جديد (${name.trim()}) - الطفل: ${student.name}`]
      );
      await client.query('COMMIT');
      const token = signToken(userRows[0]);
      const { password: _, ...safeUser } = userRows[0];
      return res.status(201).json({ token, user: safeUser });
    }

    // ── TEACHER ───────────────────────────────────────────────
    if (role === 'teacher') {
      if (phone && !isValidPhone(phone)) return res.status(400).json({ error: 'رقم الجوال يجب أن يكون 10 أرقام ويبدأ بـ 0' });

      const { rows: teachers } = await client.query(
        'SELECT id, name, invite_code_hash FROM teachers WHERE invite_code_hash IS NOT NULL'
      );
      const teacher = teachers.find((t) => bcrypt.compareSync(normalizedCode, t.invite_code_hash));
      if (!teacher) return res.status(400).json({ error: 'رمز الدعوة غير صحيح' });

      const alreadyUsed = await client.query('SELECT id FROM users WHERE teacher_id = $1', [teacher.id]);
      if (alreadyUsed.rows.length > 0)
        return res.status(409).json({ error: 'تم استخدام هذا الرمز بالفعل' });

      const classRes = await client.query('SELECT id FROM classes WHERE teacher_id = $1 LIMIT 1', [teacher.id]);
      const classId = classRes.rows[0]?.id || null;

      await client.query('BEGIN');
      // Update teacher record with email and phone (if provided)
      if (phone) {
        await client.query('UPDATE teachers SET email = $1, phone = $2 WHERE id = $3', [email, phone.trim(), teacher.id]);
      } else {
        await client.query('UPDATE teachers SET email = $1 WHERE id = $2', [email, teacher.id]);
      }
      const hashed = bcrypt.hashSync(password, 10);
      const { rows: userRows } = await client.query(
        `INSERT INTO users (name, email, password, role, avatar, class_id, teacher_id, invite_code)
         VALUES ($1, $2, $3, 'teacher', '👩‍🏫', $4, $5, $6) RETURNING *`,
        [teacher.name, email, hashed, classId, teacher.id, normalizedCode]
      );
      await client.query(
        `INSERT INTO activity_log (icon, text, type) VALUES ('👩‍🏫', $1, 'user')`,
        [`معلمة جديدة: ${teacher.name}`]
      );
      await client.query('COMMIT');
      const token = signToken(userRows[0]);
      const { password: _, ...safeUser } = userRows[0];
      return res.status(201).json({ token, user: safeUser });
    }
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    console.error('Register error:', err);
    res.status(500).json({ error: 'خطأ في إنشاء الحساب' });
  } finally {
    client.release();
  }
});

// ── GET /api/auth/me ──────────────────────────────────────────
router.get('/me', verifyToken, async (req, res) => {
  try {
    const { rows } = await db.query('SELECT * FROM users WHERE id = $1', [req.user.id]);
    if (!rows[0]) return res.status(404).json({ error: 'المستخدم غير موجود' });
    const { password: _, ...safeUser } = rows[0];
    res.json(safeUser);
  } catch (err) {
    res.status(500).json({ error: 'خطأ في جلب بيانات المستخدم' });
  }
});

// ── POST /api/auth/forgot-password ───────────────────────────
// This route is kept for the reset-password step — the reset key is generated by the manager.
// It simply verifies the email exists so the frontend can proceed to the code-entry step.
router.post('/forgot-password', async (req, res) => {
  // Always return success regardless of whether email exists (prevents enumeration)
  res.json({ success: true });
});

// ── POST /api/auth/reset-password ─────────────────────────────
router.post('/reset-password', async (req, res) => {
  try {
    const { email, otp, newPassword } = req.body;
    if (!email || !otp || !newPassword)
      return res.status(400).json({ error: 'جميع الحقول مطلوبة' });
    if (newPassword.length < 6)
      return res.status(400).json({ error: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل' });

    const { rows } = await db.query(
      'SELECT id, reset_token, reset_token_expiry FROM users WHERE LOWER(email) = LOWER($1)',
      [email]
    );
    const user = rows[0];
    if (!user || !user.reset_token)
      return res.status(400).json({ error: 'الرمز غير صحيح أو منتهي الصلاحية' });

    // Check expiry
    if (new Date(user.reset_token_expiry) < new Date())
      return res.status(400).json({ error: 'انتهت صلاحية الرمز — يرجى طلب رمز جديد' });

    // Verify OTP
    const valid = bcrypt.compareSync(otp.trim(), user.reset_token);
    if (!valid)
      return res.status(400).json({ error: 'الرمز غير صحيح' });

    const hashed = bcrypt.hashSync(newPassword, 10);
    await db.query(
      'UPDATE users SET password = $1, reset_token = NULL, reset_token_expiry = NULL WHERE id = $2',
      [hashed, user.id]
    );
    res.json({ success: true, message: 'تم تغيير كلمة المرور بنجاح' });
  } catch (err) {
    console.error('reset-password error:', err);
    res.status(500).json({ error: 'خطأ في إعادة تعيين كلمة المرور' });
  }
});

// ── POST /api/auth/change-password ────────────────────────────
// Authenticated: user must know their current password
router.post('/change-password', verifyToken, async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;
    if (!currentPassword || !newPassword)
      return res.status(400).json({ error: 'جميع الحقول مطلوبة' });
    if (newPassword.length < 6)
      return res.status(400).json({ error: 'كلمة المرور الجديدة يجب أن تكون 6 أحرف على الأقل' });

    const { rows } = await db.query('SELECT password FROM users WHERE id = $1', [req.user.id]);
    if (!rows[0]) return res.status(404).json({ error: 'المستخدم غير موجود' });

    const valid = bcrypt.compareSync(currentPassword, rows[0].password);
    if (!valid)
      return res.status(401).json({ error: 'كلمة المرور الحالية غير صحيحة' });

    const hashed = bcrypt.hashSync(newPassword, 10);
    await db.query('UPDATE users SET password = $1 WHERE id = $2', [hashed, req.user.id]);
    res.json({ success: true, message: 'تم تغيير كلمة المرور بنجاح' });
  } catch (err) {
    console.error('change-password error:', err);
    res.status(500).json({ error: 'خطأ في تغيير كلمة المرور' });
  }
});

module.exports = router;

